#!/usr/bin/env bash

PICTURE=~/Pictures/sky.png
# SCREENSHOT="scrot -z $PICTURE"

BLUR="5x4"

# "$SCREENSHOT"
convert "$PICTURE" -blur "$BLUR" "$PICTURE"
i3lock -i "$PICTURE"
# rm "$PICTURE"


# xss-lock --transfer-sleep-lock -- i3lock --nofork -i ~/Pictures/sky.png
