#!/usr/bin/perl

use strict;
use warnings;
use utf8;
use Getopt::Long;

my $t_warn = $ENV{T_WARN} // 50;
my $t_crit = $ENV{T_CRIT} // 80;
my $decimals = $ENV{DECIMALS} // 0;
my $label = $ENV{LABEL} // "";
my $cpu_usage = -1;

sub help {
    print "Usage: cpu_usage [-w <warning>] [-c <critical>] [-d <decimals>]\n";
    exit 0;
}

GetOptions(
    "help|h" => \&help,
    "w=i"    => \$t_warn,
    "c=i"    => \$t_crit,
    "d=i"    => \$decimals,
);

# Force en_US locale for consistent output
$ENV{LC_ALL} = "en_US.UTF-8";

open(my $MP, "-|", "mpstat 1 1") or die "Failed to run mpstat: $!";
my $header;
while (<$MP>) {
    chomp;
    if (/^.*%idle/) {
        $header = $_;
        next;
    }
    if (defined $header && /\ball\b|\d+/) {
        my @cols = split(/\s+/, $_);
        $cpu_usage = 100 - $cols[-1];
        last;
    }
}
close($MP);

$cpu_usage == -1 and die "Can't find CPU information from mpstat output\n";

# Output text
print "${label}";
printf "%02.${decimals}f%%\n", $cpu_usage;
print "${label}";
printf "%02.${decimals}f%%\n", $cpu_usage;

# Output color
if ($cpu_usage >= $t_crit) {
    print "#FF0000\n";
    exit 33;
} elsif ($cpu_usage >= $t_warn) {
    print "#FFFC00\n";
}

exit 0;
