#!/bin/bash

Main() {
    source /usr/share/endeavouros/scripts/eos-script-lib-yad || return 1

    local command=(
        eos_yad --title="EndeavourOS i3-wm keybindings:" --no-buttons --geometry=400x345-15-400 --list
        --column=key: --column=description: --column=command:
        "ESC" "close this app" ""
        "=" "modkey" "(set mod Mod4)"
        "+Enter" "open a terminal" ""
        "+Shift+n" "new empty workspace" ""
        "+e" "open Filebrowser" ""
        "+Space" "app menu" ""
        "+q" "close focused app" ""
        "Print-key" "screenshot" ""
        "+Print-key" "screenshot current window" ""
        "+Shift+e" "logout menu" ""
        "F1" "open keybinding helper" ""
    )

    "${command[@]}"
}

Main "$@"
