#!/usr/bin/env bash

# Script to get city weather data from OpenWeaterMap

# Get the directory of the current script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load .env file to the script
if [ -f "$SCRIPT_DIR/.env" ]; then
	source "$SCRIPT_DIR/.env"
else
	echo "You need to create a .env file in $SCRIPT_DIR. Aborting.."
	exit 1
fi

# Check if API key and CityID are set
if [[ -z "$API_KEY" || -z "$CITY_ID" ]]; then
	echo "API_KEY or CITY_ID is missing in the .env file. Aborting."
	exit 1
fi

command -v jq >/dev/null 2>&1 || {
	echo >&2 "Program 'jq' required but it is not installed.
Aborting."
	exit 1
}
command -v curl >/dev/null 2>&1 || {
	echo >&2 "Program 'curl' required but is not installed.
Aborting."
	exit 1
}

# To use this script you need to create an API key here https://home.openweathermap.org
# find your City ID here: https://openweathermap.org/
# search for your city and copy the ID from the URL inside the browser.
# You need to copy the .env.example file to .env
URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&units=metric&APPID=${API_KEY}"

WEATHER_RESPONSE=$(timeout --signal=1 6s curl -s "$URL") || exit 1

WEATHER_CONDITION=$(echo "$WEATHER_RESPONSE" | jq '.weather[0].main' | sed 's/"//g')
WEATHER_TEMP=$(echo "$WEATHER_RESPONSE" | jq '.main.temp')
WIND_DIR=$(echo "$WEATHER_RESPONSE" | jq '.wind.deg')
WIND_SPEED=$(echo "$WEATHER_RESPONSE" | jq '.wind.speed')

WIND_SPEED=$(awk "BEGIN {print 60*60*$WIND_SPEED/1000}")
WIND_DIR=$(awk "BEGIN {print int(($WIND_DIR % 360)/22.5)}")
DIR_ARRAY=(N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N)
WIND_DIR=${DIR_ARRAY[WIND_DIR]}

case $WEATHER_CONDITION in
'Clouds')
	WEATHER_ICON=""
	;;
'Rain')
	WEATHER_ICON=""
	;;
'Snow')
	WEATHER_ICON=""
	;;
*)
	WEATHER_ICON=""
	;;
esac

echo "${WEATHER_ICON}  ${WEATHER_TEMP}°C: ${WIND_SPEED} km/h ${WIND_DIR}"
