#!/bin/bash
# original source: https://gitlab.com/Nmoleo/i3-volume-brightness-indicator

volume_step=1
brightness_step=5
max_volume=100
notif_id=1001 # Unique ID for notification replacement

# Uses regex to get volume from pactl
function get_volume {
	pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1
}

# Uses regex to get mute status from pactl
function get_mute {
	pactl get-sink-mute @DEFAULT_SINK@ | grep -Po '(?<=Mute: )(yes|no)'
}

# Uses regex to get brightness from xbacklight
function get_brightness {
	brightnessctl get | head -n 1
}

# Returns a mute icon, a volume-low icon, or a volume-high icon, depending on the volume
function get_volume_icon {
	volume=$(get_volume)
	mute=$(get_mute)
	if [ "$volume" -eq 0 ] || [ "$mute" == "yes" ]; then
		volume_icon=""
	elif [ "$volume" -lt 50 ]; then
		volume_icon=""
	else
		volume_icon=""
	fi
}

# Always returns the same icon
function get_brightness_icon {
	brightness_icon=""
}

# Displays a volume notification using notify-send
function show_volume_notif {
	volume=$(get_volume)
	get_volume_icon
	notify-send -u low -r "$notif_id" "$volume_icon    " -h int:value:"$volume"
}

# Displays a brightness notification using notify-send
function show_brightness_notif {
	brightness_raw=$(get_brightness)
    # Because the ax brightness is 255 on this thinkpad,
    # we need to adjust for dunst notifications.
    brightness=$(printf "%.0f" $(echo "scale=2; ($brightness_raw/255) * 100" | bc -l))
	get_brightness_icon
	notify-send -u low -r "$notif_id" "$brightness_icon    " -h int:value:"$brightness"
}

# Main function - Takes user input
case $1 in
volume_up)
	pactl set-sink-mute @DEFAULT_SINK@ 0
	volume=$(get_volume)
	if [ $(("$volume" + "$volume_step")) -gt "$max_volume" ]; then
		pactl set-sink-volume @DEFAULT_SINK@ "$max_volume"%
	else
		pactl set-sink-volume @DEFAULT_SINK@ +"$volume_step"%
	fi
	show_volume_notif
	;;

volume_down)
	pactl set-sink-volume @DEFAULT_SINK@ -"$volume_step"%
	show_volume_notif
	;;

volume_mute)
	pactl set-sink-mute @DEFAULT_SINK@ toggle
	show_volume_notif
	;;

brightness_up)
	brightnessctl set +$brightness_step%
	show_brightness_notif
	;;

brightness_down)
	brightnessctl set $brightness_step%-
	show_brightness_notif
	;;
esac
